version: '3.2'

services:
  dbasql1:
    build:
      context: ./
    image: precon
    ports:
      - target: 1433
        protocol: tcp
        mode: host
      - target: 5985
        protocol: tcp
        mode: host
      - target: 5986
        protocol: tcp
        mode: host
    container_name: dbasql1
    env_file:
     - ./env
  dbasql2:
    build:
      context: ./
    image: precon
    ports:
      - target: 1433
        protocol: tcp
        mode: host
      - target: 5985
        protocol: tcp
        mode: host
      - target: 5986
        protocol: tcp
        mode: host
    container_name: dbasql2
    env_file:
     - ./env
  dbasql3:
     build:
       context: ./
     image: precon
     ports:
       - target: 1433
         protocol: tcp
         mode: host
       - target: 5985
         protocol: tcp
         mode: host
       - target: 5986
         protocol: tcp
         mode: host
     container_name: dbasql3
     env_file:
      - ./env
  dbasql4:
     build:
       context: ./
     image: precon
     ports:
       - target: 1433
         protocol: tcp
         mode: host
       - target: 5985
         protocol: tcp
         mode: host
       - target: 5986
         protocol: tcp
         mode: host
     container_name: dbasql4
     env_file:
      - ./env
  dbasql5:
        build:
          context: ./
        image: precon
        ports:
          - target: 1433
            protocol: tcp
            mode: host
          - target: 5985
            protocol: tcp
            mode: host
          - target: 5986
            protocol: tcp
            mode: host
        container_name: dbasql5
        env_file:
         - ./env