version: '3.7'

services:
    dbatoolssql1:
        image: dbatools/sqlinstance
        ports:  
          - "15591:1433"
          - "5022:5022"
        volumes: 
          - C:\MSSQL\BACKUP\KEEP:/var/opt/mssql/backups
        networks: 
          - dbatoolsatpass
    dbatoolssql2:
        image: dbatools/sqlinstance2
        ports:  
          - "15592:1433"
          - "5023:5023"
        volumes: 
          - C:\MSSQL\BACKUP\KEEP:/var/opt/mssql/backups
        networks: 
          - dbatoolsatpass
    theoldbeardapplication:
        image: mcr.microsoft.com/mssql/server:2019-CTP3.2-ubuntu
        ports:  
          - "16001:1433"
        environment:
          SA_PASSWORD: "Password0!"
          ACCEPT_EULA: "Y"
        volumes: 
          - C:\MSSQL\BACKUP\KEEP:/var/opt/mssql/backups
        networks: 
          - dbatoolsatpass
networks:
  dbatoolsatpass:
    name: dbatoolsatpassnetwork
