name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 
      - dockerfile
      - Game/profile.ps1
      - Game/JessAndBeard.psm1
    
  pull_request:
    branches: [ main ]
    paths:
      - dockerfile
      - Game/profile.ps1
      - Game/JessAndBeard.psm1
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DEFAULT_BUMP: minor
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dbatoolsprecon:${{ steps.bump.outputs.new_tag }}
